name: Build

# Define o evento que desencadeará o fluxo de trabalho
on:
  push:
    branches:
      - main

# Define o trabalho a ser executado
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Define as etapas a serem executadas
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: haxelib install all

    - name: Build game
      run: lime build build.yaml
